s_ext = {
    "extension": "{\"targetNo\":\"16\"}",
    "noSelloutRoomRpList": [
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "1张大床1.8米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "0DNHWV",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-3层",
          "goodsId": "733462052PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "40",
          "original_price": "492",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "8",
          "roomName": "池景花园大床房",
          "roomType": "0",
          "room_price": "492",
          "roomid": "250666499",
          "title": "池景花园大床房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "0DNHXB",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-3层",
          "goodsId": "733462057PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "39",
          "original_price": "493",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "4",
          "roomName": "池景花园双床房",
          "roomType": "0",
          "room_price": "493",
          "roomid": "250666609",
          "title": "池景花园双床房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "1张大床1.8米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "0DNOBT",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-3层",
          "goodsId": "733464786FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "38",
          "original_price": "500",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "8",
          "roomName": "池景花园大床房",
          "roomType": "0",
          "room_price": "500",
          "roomid": "250666499",
          "title": "池景花园大床房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "0DNOBR",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-3层",
          "goodsId": "733464783FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "37",
          "original_price": "501",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "4",
          "roomName": "池景花园双床房",
          "roomType": "0",
          "room_price": "501",
          "roomid": "250666609",
          "title": "池景花园双床房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OKMT0",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-3层",
          "goodsId": "949462356FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "36",
          "original_price": "591",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "4",
          "roomName": "池景花园双床房",
          "roomType": "0",
          "room_price": "591",
          "roomid": "250666609",
          "title": "池景花园双床房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "1张大床1.8米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OKMT1",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-3层",
          "goodsId": "949462346FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "35",
          "original_price": "591",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "8",
          "roomName": "池景花园大床房",
          "roomType": "0",
          "room_price": "591",
          "roomid": "250666499",
          "title": "池景花园大床房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OK9OV",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-3层",
          "goodsId": "949464788PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "34",
          "original_price": "594",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "4",
          "roomName": "池景花园双床房",
          "roomType": "0",
          "room_price": "594",
          "roomid": "250666609",
          "title": "池景花园双床房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "1张大床1.8米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OK9OZ",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-3层",
          "goodsId": "949464777PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "33",
          "original_price": "595",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "8",
          "roomName": "池景花园大床房",
          "roomType": "0",
          "room_price": "595",
          "roomid": "250666499",
          "title": "池景花园大床房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "PJLL6",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-13层",
          "goodsId": "59730351FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "32",
          "original_price": "627",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景大床房",
          "roomType": "0",
          "room_price": "627",
          "roomid": "30827812",
          "title": "豪华精品海景大床房",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "PJLLI",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-13层",
          "goodsId": "59730354FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "31",
          "original_price": "631",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景双床房",
          "roomType": "0",
          "room_price": "631",
          "roomid": "30827810",
          "title": "豪华精品海景双床房",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "D0G8AW",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-13层",
          "goodsId": "262838733PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "30",
          "original_price": "656",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景大床房",
          "roomType": "0",
          "room_price": "656",
          "roomid": "30827812",
          "title": "豪华精品海景大床房",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "D0GJ2R",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-13层",
          "goodsId": "262839663PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "29",
          "original_price": "658",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景双床房",
          "roomType": "0",
          "room_price": "658",
          "roomid": "30827810",
          "title": "豪华精品海景双床房",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77BBP",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3层",
          "goodsId": "1116012887FG",
          "goodsStatus": "17",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "28",
          "original_price": "735",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "1",
          "roomName": "亲子幻游太空双标房",
          "roomType": "0",
          "room_price": "735",
          "roomid": "329067407",
          "title": "亲子幻游太空双标房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77B2H",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3层",
          "goodsId": "1116013306PP",
          "goodsStatus": "17",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "27",
          "original_price": "738",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "1",
          "roomName": "亲子幻游太空双标房",
          "roomType": "0",
          "room_price": "738",
          "roomid": "329067407",
          "title": "亲子幻游太空双标房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OKMTW",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-13层",
          "goodsId": "949462377FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "26",
          "original_price": "760",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景大床房",
          "roomType": "0",
          "room_price": "760",
          "roomid": "30827812",
          "title": "豪华精品海景大床房",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OKMTH",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-13层",
          "goodsId": "949462366FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "25",
          "original_price": "762",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景双床房",
          "roomType": "0",
          "room_price": "762",
          "roomid": "30827810",
          "title": "豪华精品海景双床房",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OK9AN",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-13层",
          "goodsId": "949464708PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "24",
          "original_price": "766",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景双床房",
          "roomType": "0",
          "room_price": "766",
          "roomid": "30827810",
          "title": "豪华精品海景双床房",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OK9AV",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-13层",
          "goodsId": "949464716PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{\"basics_room_type\":\"1\"}",
          "lowest3Room": "true",
          "onSaleOrange": "[],",
          "orderByRank": "23",
          "original_price": "770",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景大床房",
          "roomType": "0",
          "room_price": "770",
          "roomid": "30827812",
          "title": "豪华精品海景大床房",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "70",
          "bed_type": "1张特大床2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77B22",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1层",
          "goodsId": "1116013297PP",
          "goodsStatus": "17",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "22",
          "original_price": "817",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "1",
          "roomName": "亲子套幻游太空（一房一厅）",
          "roomType": "0",
          "room_price": "817",
          "roomid": "329037861",
          "title": "亲子套幻游太空（一房一厅）",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "70",
          "bed_type": "1张特大床2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77BBW",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1层",
          "goodsId": "1116012885FG",
          "goodsStatus": "17",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "21",
          "original_price": "819",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "1",
          "roomName": "亲子套幻游太空（一房一厅）",
          "roomType": "0",
          "room_price": "819",
          "roomid": "329037861",
          "title": "亲子套幻游太空（一房一厅）",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77B1B",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3层",
          "goodsId": "1116012889FG",
          "goodsStatus": "17",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "20",
          "original_price": "825",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "1",
          "roomName": "亲子幻游太空双标房",
          "roomType": "0",
          "room_price": "825",
          "roomid": "329067407",
          "title": "亲子幻游太空双标房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "48",
          "bed_type": "2张单人床1.2米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77B2O",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3层",
          "goodsId": "1116013309PP",
          "goodsStatus": "17",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "19",
          "original_price": "827",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "1",
          "roomName": "亲子幻游太空双标房",
          "roomType": "0",
          "room_price": "827",
          "roomid": "329067407",
          "title": "亲子幻游太空双标房",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "70",
          "bed_type": "1张特大床2米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77B2G",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1层",
          "goodsId": "1116013301PP",
          "goodsStatus": "17",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "18",
          "original_price": "912",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "1",
          "roomName": "亲子套幻游太空（一房一厅）",
          "roomType": "0",
          "room_price": "912",
          "roomid": "329037861",
          "title": "亲子套幻游太空（一房一厅）",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "70",
          "bed_type": "1张特大床2米",
          "breakfast": "2份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77BBX",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1层",
          "goodsId": "1116012886FG",
          "goodsStatus": "17",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "17",
          "original_price": "914",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住2人",
          "promotionSrc": "[]",
          "roomLast": "1",
          "roomName": "亲子套幻游太空（一房一厅）",
          "roomType": "0",
          "room_price": "914",
          "roomid": "329037861",
          "title": "亲子套幻游太空（一房一厅）",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "4张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "BBXKQ3",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-2层",
          "goodsId": "63745992PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "16",
          "original_price": "1072",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "池景花园二居套",
          "roomType": "0",
          "room_price": "1072",
          "roomid": "35309314",
          "title": "池景花园二居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "4张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "BBXKO7",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-2层",
          "goodsId": "63745972FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "15",
          "original_price": "1072",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "池景花园二居套",
          "roomType": "0",
          "room_price": "1072",
          "roomid": "35309314",
          "title": "池景花园二居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "PJLL7",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-12层",
          "goodsId": "59730352FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "14",
          "original_price": "1203",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景二居套",
          "roomType": "0",
          "room_price": "1203",
          "roomid": "30827815",
          "title": "豪华精品海景二居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "4张单人床1.2米",
          "breakfast": "4份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OKMVC",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-2层",
          "goodsId": "949462419FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "13",
          "original_price": "1237",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "池景花园二居套",
          "roomType": "0",
          "room_price": "1237",
          "roomid": "35309314",
          "title": "池景花园二居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "PJ26R",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-12层",
          "goodsId": "59737095PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "12",
          "original_price": "1245",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景二居套",
          "roomType": "0",
          "room_price": "1245",
          "roomid": "30827815",
          "title": "豪华精品海景二居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "4张单人床1.2米",
          "breakfast": "4份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OK9NW",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "1-2层",
          "goodsId": "949464753PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "11",
          "original_price": "1263",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "池景花园二居套",
          "roomType": "0",
          "room_price": "1263",
          "roomid": "35309314",
          "title": "池景花园二居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77B11",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "7-10层",
          "goodsId": "1116012890FG",
          "goodsStatus": "0",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "10",
          "original_price": "1369",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "3",
          "roomName": "豪华海景海底世界亲子家庭套（二房一厅）",
          "roomType": "0",
          "room_price": "1369",
          "roomid": "329117364",
          "title": "豪华海景海底世界亲子家庭套（二房一厅）",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77B2U",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "7-10层",
          "goodsId": "1116013315PP",
          "goodsStatus": "0",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "9",
          "original_price": "1385",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "3",
          "roomName": "豪华海景海底世界亲子家庭套（二房一厅）",
          "roomType": "0",
          "room_price": "1385",
          "roomid": "329117364",
          "title": "豪华海景海底世界亲子家庭套（二房一厅）",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "4份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OKMUG",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-12层",
          "goodsId": "949462397FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "8",
          "original_price": "1406",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景二居套",
          "roomType": "0",
          "room_price": "1406",
          "roomid": "30827815",
          "title": "豪华精品海景二居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "4份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6E5HW3",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "3-12层",
          "goodsId": "917333316PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "7",
          "original_price": "1415",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "豪华精品海景二居套",
          "roomType": "0",
          "room_price": "1415",
          "roomid": "30827815",
          "title": "豪华精品海景二居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "4份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77B2P",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "7-10层",
          "goodsId": "1116013319PP",
          "goodsStatus": "0",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "6",
          "original_price": "1561",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "3",
          "roomName": "豪华海景海底世界亲子家庭套（二房一厅）",
          "roomType": "0",
          "room_price": "1561",
          "roomid": "329117364",
          "title": "豪华海景海底世界亲子家庭套（二房一厅）",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "100",
          "bed_type": "床型由酒店前台随机安排",
          "breakfast": "4份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "I77B1D",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "7-10层",
          "goodsId": "1116012892FG",
          "goodsStatus": "0",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "5",
          "original_price": "1571",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住4人",
          "promotionSrc": "[]",
          "roomLast": "3",
          "roomName": "豪华海景海底世界亲子家庭套（二房一厅）",
          "roomType": "0",
          "room_price": "1571",
          "roomid": "329117364",
          "title": "豪华海景海底世界亲子家庭套（二房一厅）",
          "wifi": "WIFI",
          "windows": "落地窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "160",
          "bed_type": "1张特大床2米和4张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "C80IT8",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "2-7层",
          "goodsId": "213895531PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "4",
          "original_price": "2481",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住6人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "180度全海景三居套",
          "roomType": "0",
          "room_price": "2481",
          "roomid": "91744385",
          "title": "180度全海景三居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "160",
          "bed_type": "1张特大床2米和4张单人床1.2米",
          "breakfast": "无早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "C8085P",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "2-7层",
          "goodsId": "213895943FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "3",
          "original_price": "2498",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住6人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "180度全海景三居套",
          "roomType": "0",
          "room_price": "2498",
          "roomid": "91744385",
          "title": "180度全海景三居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "160",
          "bed_type": "1张特大床2米和4张单人床1.2米",
          "breakfast": "6份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6OKMV2",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "2-7层",
          "goodsId": "949462429FG",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "2",
          "original_price": "2671",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "到店付",
          "person": "每间最多入住6人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "180度全海景三居套",
          "roomType": "0",
          "room_price": "2671",
          "roomid": "91744385",
          "title": "180度全海景三居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      },
      {
        "roomInfoPriceList": {
          "agent": "false",
          "area_size": "160",
          "bed_type": "1张特大床2米和4张单人床1.2米",
          "breakfast": "6份早餐",
          "canOrder": "可预定",
          "cancel": "",
          "encryptedRoomId": "6E5HWE",
          "feePolicy": "西式、中式早餐 ￥68.00 /人·次|￥400/人·晚",
          "floor": "2-7层",
          "goodsId": "917333322PP",
          "goodsStatus": "16",
          "hotelId": "345088",
          "isBasic": "{}",
          "onSaleOrange": "[],",
          "orderByRank": "1",
          "original_price": "2705",
          "packageDesc": "[{\"type\":4,\"value\":\"\",\"key\":\"海棠湾免税店往返接送免费巴士礼包1份+精美旅拍1份\"}]",
          "paymentTxt": "在线付",
          "person": "每间最多入住6人",
          "promotionSrc": "[]",
          "roomLast": "10",
          "roomName": "180度全海景三居套",
          "roomType": "0",
          "room_price": "2705",
          "roomid": "91744385",
          "title": "180度全海景三居套",
          "wifi": "WIFI",
          "windows": "有窗"
        }
      }
    ],
    "selloutRoomRpList": []
  }
  ;

function detail_task_deliver(s_ext, record_element) {
    var obj = JSON.parse(s_ext);
    var extension = JSON.parse(obj.extension);
    var record_element = JSON.parse(record_element);
    var result = {};
    var data = {};
    if (JSON.stringify(extension.targetNo).length < 1) {
      return "目标不符合";
    }
    if (extension.targetNo !== '16' && extension.targetNo !== '61' && extension.targetNo !== '62' && extension.targetNo !== 'ctrip-detail-true-D0AD4F385882424CAA2BF43A283DC91A' && extension.targetNo !== '88' && extension.targetNo !== '105' && extension.targetNo !== '106' && extension.targetNo !== '35') {
      return "目标不符合";
    }
    // 过滤出其中是基础房型的部分
    var filteredList = obj.noSelloutRoomRpList.filter(function (item) {
      return JSON.stringify(item.roomInfoPriceList.isBasic) !== '"{}"' && JSON.stringify(item.roomInfoPriceList.isBasic) !== '' && JSON.stringify(item.roomInfoPriceList.isBasic) !== '{}' && item.roomInfoPriceList.isBasic && item.roomInfoPriceList.canOrder != '订完';
    });
  
    // 统计每个房型的早餐数量
    var roomBreakfastCountMap = {};
    var rp_list = [];
    filteredList.forEach(function (item) {
      var roomid = item.roomInfoPriceList.roomid;
      var breakfast = item.roomInfoPriceList.breakfast;
      if (!roomBreakfastCountMap[roomid]) {
        roomBreakfastCountMap[roomid] = [];
        item.roomInfoPriceList.good_id = item.roomInfoPriceList.goodsId;
        rp_list.push({
          "room_name": item.roomInfoPriceList.roomName,
          "room_id": item.roomInfoPriceList.roomid,
          "rp_code": item.roomInfoPriceList.encryptedRoomId,
          "rp_info": item.roomInfoPriceList
        });
      }
      if (roomBreakfastCountMap[roomid].indexOf(breakfast) < 0) {
        roomBreakfastCountMap[roomid].push(breakfast);
      }
    });
    today = new Date();
    year = today.getFullYear();
    month = today.getMonth() + 1;
    day = today.getDate();
    formattedDate = "".concat(year, "-").concat(month < 10 ? '0' + month : month, "-").concat(day < 10 ? '0' + day : day);
  
    // 默认目标是低价房型target,如果判断但房型有多rp，则改为全rp任务
    var taskTarget = "ctrip-detail-true-07029F3539C444899288F27B11B76C5B";
    for (var roomid in roomBreakfastCountMap) {
      if (roomBreakfastCountMap.hasOwnProperty(roomid) && roomBreakfastCountMap[roomid].length > 1) {
        taskTarget = "ctrip-detail-true-FC63ECC7E7E54E0C9536A3768B8AB25E";
      }
    }


    // result.target = taskTarget;
    // result.duplicateTime = 300000;
    // result.shid = record_element.shid;
    // result.checkin_offset = Math.floor(Math.abs(new Date(record_element.checkinDate).getTime() - new Date(formattedDate).getTime()) / (1000 * 3600 * 24)).toString();
    // result.checkout_offset = Math.floor(Math.abs(new Date(record_element.checkoutDate).getTime() - new Date(formattedDate).getTime()) / (1000 * 3600 * 24)).toString();
    // result.compete_hotel_id = record_element.hotelId;
    // result.compete_hotel_name = record_element.hotelName;
    // result.compete_hotel_star = record_element.hotelStar;
    // result.compete_city_id = record_element.cityId;
    // result.compete_city_name = record_element.cityName;
    // result.in_china = true;
    // result.login = 'login';
    // result.isCheckParam = false;
    // result.isFilterCover = false;
    // result.data_time = record_element.dataTime;
    // result.rp_info_list = JSON.stringify(rp_list);
    // result.empty_rp_list = JSON.stringify(obj.selloutRoomRpList);


    data.destination = record_element.cityName;
    data.biz_id = record_element.hotelId;
    data.destination_city_id = record_element.cityId;
    data.destination_city_name = record_element.cityName;
    data.hotel_id = record_element.hotelId;
    data.hotel_name = record_element.hotelName;;
    data.fliggy_hotel_id = record_element.shid;
    data.origin_time = record_element.checkinDate.replace(/-/g, "");
    data.destination_time =  record_element.checkoutDate.replace(/-/g, "");

    result.data = data;
    result.strategy_id = "9";
    // 补充相应的信息
    return JSON.stringify(result);
  }




  console.log(detail_task_deliver(s_ext, ''));